name: rust_lib_wcash_warden
description: Native Cargokit loader for the isolated Wcash Warden Testnet bridge.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.11.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
