// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

/// Returns the compiled-in identity of Wcash Testnet.
WardenNetworkIdentity networkIdentity() =>
    WardenRust.instance.api.crateApiNetworkIdentity();

/// Attests the fixed TLS endpoint against Wcash Testnet identity.
///
/// The caller cannot provide an endpoint or select another network.
Future<WardenEndpointAttestation> attestEndpoint() =>
    WardenRust.instance.api.crateApiAttestEndpoint();

/// Derives Wcash Testnet receive and mining addresses in memory.
///
/// The bridge does not persist or log the mnemonic. This Testnet-only preview
/// is not a wallet and must not be used with a phrase that protects real funds.
WardenAddresses deriveAddresses({
  required String mnemonic,
  required int accountIndex,
}) => WardenRust.instance.api.crateApiDeriveAddresses(
  mnemonic: mnemonic,
  accountIndex: accountIndex,
);

/// Public addresses derived for one Wcash Testnet account.
class WardenAddresses {
  /// ZIP-32 account index used for derivation.
  final int accountIndex;

  /// Private Wcash Unified Address for Ironwood receipts.
  final String privateReceiveAddress;

  /// Transparent P2PKH address for pool-compatible coinbase payouts.
  final String transparentMiningAddress;

  const WardenAddresses({
    required this.accountIndex,
    required this.privateReceiveAddress,
    required this.transparentMiningAddress,
  });

  @override
  int get hashCode =>
      accountIndex.hashCode ^
      privateReceiveAddress.hashCode ^
      transparentMiningAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WardenAddresses &&
          runtimeType == other.runtimeType &&
          accountIndex == other.accountIndex &&
          privateReceiveAddress == other.privateReceiveAddress &&
          transparentMiningAddress == other.transparentMiningAddress;
}

/// Result of attesting the fixed Wcash Testnet wallet endpoint.
class WardenEndpointAttestation {
  /// Exact endpoint that passed Wcash chain attestation.
  final String endpoint;

  /// Human-readable accepted network name.
  final String networkName;

  /// Accepted Wcash consensus branch ID.
  final String consensusBranchId;

  /// Accepted frozen genesis hash.
  final String genesisHash;

  /// Best chain height reported at attestation time.
  final int tipHeight;

  /// Best chain hash reported at attestation time.
  final String tipHash;

  const WardenEndpointAttestation({
    required this.endpoint,
    required this.networkName,
    required this.consensusBranchId,
    required this.genesisHash,
    required this.tipHeight,
    required this.tipHash,
  });

  @override
  int get hashCode =>
      endpoint.hashCode ^
      networkName.hashCode ^
      consensusBranchId.hashCode ^
      genesisHash.hashCode ^
      tipHeight.hashCode ^
      tipHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WardenEndpointAttestation &&
          runtimeType == other.runtimeType &&
          endpoint == other.endpoint &&
          networkName == other.networkName &&
          consensusBranchId == other.consensusBranchId &&
          genesisHash == other.genesisHash &&
          tipHeight == other.tipHeight &&
          tipHash == other.tipHash;
}

/// Immutable identity of the only network available to Wcash Warden.
class WardenNetworkIdentity {
  /// Human-readable product network name.
  final String networkName;

  /// BIP70/RPC chain identifier expected from the wallet service.
  final String rpcChainName;

  /// Currency ticker for valueless Testnet coins.
  final String ticker;

  /// Number of decimal places in one TWC.
  final int decimals;

  /// Fixed TLS wallet service endpoint.
  final String endpoint;

  /// Wcash Testnet consensus branch ID in RPC display order.
  final String consensusBranchId;

  /// Frozen genesis hash in conventional display order.
  final String genesisHash;

  /// Isolated persistent-state namespace reserved for this app.
  final String storageNamespace;

  /// Prefix of private Wcash Testnet Unified Addresses.
  final String privateAddressPrefix;

  /// Prefix of transparent mining addresses.
  final String miningAddressPrefix;

  const WardenNetworkIdentity({
    required this.networkName,
    required this.rpcChainName,
    required this.ticker,
    required this.decimals,
    required this.endpoint,
    required this.consensusBranchId,
    required this.genesisHash,
    required this.storageNamespace,
    required this.privateAddressPrefix,
    required this.miningAddressPrefix,
  });

  @override
  int get hashCode =>
      networkName.hashCode ^
      rpcChainName.hashCode ^
      ticker.hashCode ^
      decimals.hashCode ^
      endpoint.hashCode ^
      consensusBranchId.hashCode ^
      genesisHash.hashCode ^
      storageNamespace.hashCode ^
      privateAddressPrefix.hashCode ^
      miningAddressPrefix.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WardenNetworkIdentity &&
          runtimeType == other.runtimeType &&
          networkName == other.networkName &&
          rpcChainName == other.rpcChainName &&
          ticker == other.ticker &&
          decimals == other.decimals &&
          endpoint == other.endpoint &&
          consensusBranchId == other.consensusBranchId &&
          genesisHash == other.genesisHash &&
          storageNamespace == other.storageNamespace &&
          privateAddressPrefix == other.privateAddressPrefix &&
          miningAddressPrefix == other.miningAddressPrefix;
}
