// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class WardenRust
    extends BaseEntrypoint<WardenRustApi, WardenRustApiImpl, WardenRustWire> {
  @internal
  static final instance = WardenRust._();

  WardenRust._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    WardenRustApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required WardenRustApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<WardenRustApiImpl, WardenRustWire>
  get apiImplConstructor => WardenRustApiImpl.new;

  @override
  WireConstructor<WardenRustWire> get wireConstructor =>
      WardenRustWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1387792623;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_wcash_warden',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class WardenRustApi extends BaseApi {
  Future<WardenEndpointAttestation> crateApiAttestEndpoint();

  WardenAddresses crateApiDeriveAddresses({
    required String mnemonic,
    required int accountIndex,
  });

  WardenNetworkIdentity crateApiNetworkIdentity();
}

class WardenRustApiImpl extends WardenRustApiImplPlatform
    implements WardenRustApi {
  WardenRustApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<WardenEndpointAttestation> crateApiAttestEndpoint() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_warden_endpoint_attestation,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAttestEndpointConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAttestEndpointConstMeta =>
      const TaskConstMeta(debugName: "attest_endpoint", argNames: []);

  @override
  WardenAddresses crateApiDeriveAddresses({
    required String mnemonic,
    required int accountIndex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_u_32(accountIndex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_warden_addresses,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDeriveAddressesConstMeta,
        argValues: [mnemonic, accountIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeriveAddressesConstMeta => const TaskConstMeta(
    debugName: "derive_addresses",
    argNames: ["mnemonic", "accountIndex"],
  );

  @override
  WardenNetworkIdentity crateApiNetworkIdentity() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_warden_network_identity,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkIdentityConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkIdentityConstMeta =>
      const TaskConstMeta(debugName: "network_identity", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WardenAddresses dco_decode_warden_addresses(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return WardenAddresses(
      accountIndex: dco_decode_u_32(arr[0]),
      privateReceiveAddress: dco_decode_String(arr[1]),
      transparentMiningAddress: dco_decode_String(arr[2]),
    );
  }

  @protected
  WardenEndpointAttestation dco_decode_warden_endpoint_attestation(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return WardenEndpointAttestation(
      endpoint: dco_decode_String(arr[0]),
      networkName: dco_decode_String(arr[1]),
      consensusBranchId: dco_decode_String(arr[2]),
      genesisHash: dco_decode_String(arr[3]),
      tipHeight: dco_decode_u_32(arr[4]),
      tipHash: dco_decode_String(arr[5]),
    );
  }

  @protected
  WardenNetworkIdentity dco_decode_warden_network_identity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return WardenNetworkIdentity(
      networkName: dco_decode_String(arr[0]),
      rpcChainName: dco_decode_String(arr[1]),
      ticker: dco_decode_String(arr[2]),
      decimals: dco_decode_u_8(arr[3]),
      endpoint: dco_decode_String(arr[4]),
      consensusBranchId: dco_decode_String(arr[5]),
      genesisHash: dco_decode_String(arr[6]),
      storageNamespace: dco_decode_String(arr[7]),
      privateAddressPrefix: dco_decode_String(arr[8]),
      miningAddressPrefix: dco_decode_String(arr[9]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WardenAddresses sse_decode_warden_addresses(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_accountIndex = sse_decode_u_32(deserializer);
    var var_privateReceiveAddress = sse_decode_String(deserializer);
    var var_transparentMiningAddress = sse_decode_String(deserializer);
    return WardenAddresses(
      accountIndex: var_accountIndex,
      privateReceiveAddress: var_privateReceiveAddress,
      transparentMiningAddress: var_transparentMiningAddress,
    );
  }

  @protected
  WardenEndpointAttestation sse_decode_warden_endpoint_attestation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_endpoint = sse_decode_String(deserializer);
    var var_networkName = sse_decode_String(deserializer);
    var var_consensusBranchId = sse_decode_String(deserializer);
    var var_genesisHash = sse_decode_String(deserializer);
    var var_tipHeight = sse_decode_u_32(deserializer);
    var var_tipHash = sse_decode_String(deserializer);
    return WardenEndpointAttestation(
      endpoint: var_endpoint,
      networkName: var_networkName,
      consensusBranchId: var_consensusBranchId,
      genesisHash: var_genesisHash,
      tipHeight: var_tipHeight,
      tipHash: var_tipHash,
    );
  }

  @protected
  WardenNetworkIdentity sse_decode_warden_network_identity(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_networkName = sse_decode_String(deserializer);
    var var_rpcChainName = sse_decode_String(deserializer);
    var var_ticker = sse_decode_String(deserializer);
    var var_decimals = sse_decode_u_8(deserializer);
    var var_endpoint = sse_decode_String(deserializer);
    var var_consensusBranchId = sse_decode_String(deserializer);
    var var_genesisHash = sse_decode_String(deserializer);
    var var_storageNamespace = sse_decode_String(deserializer);
    var var_privateAddressPrefix = sse_decode_String(deserializer);
    var var_miningAddressPrefix = sse_decode_String(deserializer);
    return WardenNetworkIdentity(
      networkName: var_networkName,
      rpcChainName: var_rpcChainName,
      ticker: var_ticker,
      decimals: var_decimals,
      endpoint: var_endpoint,
      consensusBranchId: var_consensusBranchId,
      genesisHash: var_genesisHash,
      storageNamespace: var_storageNamespace,
      privateAddressPrefix: var_privateAddressPrefix,
      miningAddressPrefix: var_miningAddressPrefix,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_warden_addresses(
    WardenAddresses self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.accountIndex, serializer);
    sse_encode_String(self.privateReceiveAddress, serializer);
    sse_encode_String(self.transparentMiningAddress, serializer);
  }

  @protected
  void sse_encode_warden_endpoint_attestation(
    WardenEndpointAttestation self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.endpoint, serializer);
    sse_encode_String(self.networkName, serializer);
    sse_encode_String(self.consensusBranchId, serializer);
    sse_encode_String(self.genesisHash, serializer);
    sse_encode_u_32(self.tipHeight, serializer);
    sse_encode_String(self.tipHash, serializer);
  }

  @protected
  void sse_encode_warden_network_identity(
    WardenNetworkIdentity self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.networkName, serializer);
    sse_encode_String(self.rpcChainName, serializer);
    sse_encode_String(self.ticker, serializer);
    sse_encode_u_8(self.decimals, serializer);
    sse_encode_String(self.endpoint, serializer);
    sse_encode_String(self.consensusBranchId, serializer);
    sse_encode_String(self.genesisHash, serializer);
    sse_encode_String(self.storageNamespace, serializer);
    sse_encode_String(self.privateAddressPrefix, serializer);
    sse_encode_String(self.miningAddressPrefix, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
